# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7ef4bc56dff5d0e876fd55cbe0aff41cacc39d59497fff8d44418d93c4293d84249057526decef2503ddfbaf99ffc761acc5f97a6138186c2f1d14249a12021c

test:
  secret_key_base: 55ac5bb2085bf1e5b4ad364c1ea5666bbbefc1a5350c29043ebbe0759d01880bd10b92800727dabd2bdd0741a662858dfae6b88e67d005bbfee80484f5116ec7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
